import 'package:flutter/foundation.dart';

import '../../../core/models/models.dart';
import '../data/budget_repository.dart';

/// Service that handles automatic budget cloning from previous months.
///
/// When a user navigates to a month with no budgets, this service
/// finds the latest prior month with data and clones budgets forward.
class BudgetCloneService {
  BudgetCloneService(this._repository);

  final BudgetRepository _repository;

  /// Returns true if the target month already has at least one budget.
  Future<bool> checkBudgetExists({
    required String householdId,
    required int month,
    required int year,
  }) {
    return _repository.hasBudgetsForMonth(
      householdId: householdId,
      month: month,
      year: year,
    );
  }

  /// Finds the latest month before target that has budget data.
  /// Returns null if no previous budgets exist (new user).
  Future<({int month, int year})?> findLatestBudgetMonth({
    required String householdId,
    required int targetMonth,
    required int targetYear,
  }) {
    return _repository.findLatestBudgetMonthBefore(
      householdId: householdId,
      month: targetMonth,
      year: targetYear,
    );
  }

  /// Clones all budgets from sourceMonth/sourceYear into targetMonth/targetYear.
  /// Copies: category_id, amount, display_order.
  /// Does NOT copy: transactions, spending, summaries, statistics.
  Future<void> cloneBudgetMonth({
    required String householdId,
    required int sourceMonth,
    required int sourceYear,
    required int targetMonth,
    required int targetYear,
    String? createdBy,
  }) async {
    final sourceBudgets = await _repository.fetchBudgetsByMonth(
      householdId: householdId,
      month: sourceMonth,
      year: sourceYear,
    );

    debugPrint('[BudgetClone] source budgets count: ${sourceBudgets.length}');

    if (sourceBudgets.isEmpty) return;

    final clonedBudgets = sourceBudgets.map((budget) {
      return Budget(
        id: '', // Will be generated by Supabase
        householdId: householdId,
        categoryId: budget.categoryId,
        month: targetMonth,
        year: targetYear,
        amount: budget.amount,
        displayOrder: budget.displayOrder,
        createdBy: createdBy,
      );
    }).toList();

    debugPrint('[BudgetClone] inserting ${clonedBudgets.length} cloned rows');

    await _repository.insertClonedBudgets(clonedBudgets);

    debugPrint('[BudgetClone] insert success');
  }

  /// Main entry point: checks if target month needs cloning, and if so,
  /// finds the source month and clones budgets automatically.
  ///
  /// Returns true if cloning was performed, false otherwise.
  Future<bool> cloneBudgetIfNeeded({
    required String householdId,
    required int month,
    required int year,
    String? createdBy,
  }) async {
    debugPrint('[BudgetClone] cloneBudgetIfNeeded called: month=$month year=$year');

    // If target month already has budgets, skip.
    final exists = await checkBudgetExists(
      householdId: householdId,
      month: month,
      year: year,
    );
    if (exists) {
      debugPrint(
        '[BudgetClone] skipped – target month $month/$year already has budgets',
      );
      return false;
    }

    debugPrint('[BudgetClone] target month is empty, searching for source...');

    // Find the latest month with budget data before target.
    final source = await findLatestBudgetMonth(
      householdId: householdId,
      targetMonth: month,
      targetYear: year,
    );
    if (source == null) {
      debugPrint(
        '[BudgetClone] skipped – no previous budget data found for household',
      );
      return false;
    }

    debugPrint(
      '[BudgetClone] cloning from ${source.month}/${source.year} → $month/$year',
    );

    await cloneBudgetMonth(
      householdId: householdId,
      sourceMonth: source.month,
      sourceYear: source.year,
      targetMonth: month,
      targetYear: year,
      createdBy: createdBy,
    );

    debugPrint('[BudgetClone] clone completed successfully');
    return true;
  }
}
